<a href="https://colab.research.google.com/github/marqueserick/ciencia-dados/blob/main/01_introducao_ao_python/05_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#facilita operaçoes matematicas
#objeto de matriz multidimensional
#possui tamanho fixo e todos elementos devem ter o mesmo tipo
import numpy as np
a = np.array([12,36,5,7,5])
print(a)
print(a.dtype)

[12 36  5  7  5]
int64


In [2]:
#cria uma matriz unidimensional
mt = np.array([12,13,134,15])
print(mt)
print(type(mt))

[ 12  13 134  15]
<class 'numpy.ndarray'>


In [3]:
#criar um array com tipo especificico
mt_float = np.array([1,2,3], dtype = np.float64)
print(mt_float)
print(type(mt_float))
mt_int = np.array([1,2,3,4], dtype = np.int32)
print(mt_int)
print(type(mt_int))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3 4]
<class 'numpy.ndarray'>


In [7]:
#converter dados do array
mt = np.array([2.33, 1.9, 9.19999])
print(mt)
mt_int = mt.astype(np.int32)
#ao fazer a conversão, os valores são truncados
print(mt_int)

#podemos fazer o inverso
mt_int = np.array([1,2,3])
print(mt_int)
mt_float = mt_int.astype(np.float64)
print(mt_float)

[2.33    1.9     9.19999]
[2 1 9]
[1 2 3]
[1. 2. 3.]


In [9]:
#array bidimensional
mt_bidimensional = np.array([[1,2,3],[2,3,4],[3,4,5]])
print(mt_bidimensional)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [14]:
#criar arrays vazias tipificadas
#empty significa que não são inicializadas, não que são vazias
vazio = np.empty([3,2], dtype = np.int32)
print(vazio, end="\n\n")
zeros = np.zeros([4,3])
print(zeros, end="\n\n")
um = np.ones([5,3])
print(um, end="\n\n")
diagonal = np.eye(5)
print(diagonal, end="\n\n")

[[ 171798692 1073914839]
 [1717986918 1073636966]
 [ 383454680 1075996261]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]



In [18]:
#gerar matriz com valores aleatorios entre 0 e 1
aleatorios = np.random.random((5))
print(aleatorios, end="\n\n")
#valores aleatórios distribuição normal com numéros negativos
aleatorios2 = np.random.randn((5))
print(aleatorios2, end="\n\n")
#valores aleatorios 3x4
aleatorios3 = np.random.random((3,4))
print(aleatorios3, end="\n\n")
#multiplicando valores aleatorios
aleatorio4 = (10*np.random.random((3,4)))
print(aleatorio4)


[0.989179   0.28919735 0.98669616 0.53243297 0.63056836]

[-0.885043    0.11156403 -0.14476384  1.05950509  0.17125566]

[[0.98087749 0.81389215 0.11280762 0.53290181]
 [0.5300036  0.51806157 0.19459804 0.4241602 ]
 [0.83409011 0.49724243 0.63667495 0.50627568]]

[[4.5672132  9.5867313  4.1102185  4.26541954]
 [1.88009838 9.65058366 2.13136691 1.69215836]
 [1.1691137  4.25185813 7.01587924 7.56481637]]


In [24]:
#outra forma de gerar aleatorio
#uso de semente
gnr = np.random.default_rng(1)
print(gnr, end="\n\n")
aleatorio5 = gnr.random(5)
print(aleatorio5)
#gerar inteiros
aleatorio6 = gnr.integers(20, size=(4,3))
print(aleatorio6)

Generator(PCG64)

[0.51182162 0.9504637  0.14415961 0.94864945 0.31183145]
[[17  8  5]
 [16  5  8]
 [12 10  1]
 [ 0 17 15]]


In [25]:
#unique remove repetições e ordena itens
j = np.array([11,12,13,14,1,12,13,5,6,8,9,11,12,11,15,4,3])
print(j)
j = np.unique(j)
print(j)

[11 12 13 14  1 12 13  5  6  8  9 11 12 11 15  4  3]
[ 1  3  4  5  6  8  9 11 12 13 14 15]


In [28]:

print(mt_bidimensional)
print(mt_bidimensional[0][1])
print(mt_bidimensional.shape)

[[1 2 3]
 [2 3 4]
 [3 4 5]]
2
(3, 3)


In [29]:
#Funções matemáticas
#retorna maior valor da matriz
print(mt_bidimensional.max())
#retorna o menor valor da matriz
print(mt_bidimensional.min())
#retorna soma dos valores da matriz
print(mt_bidimensional.sum())
#retorna a média dos valores da matriz
print(mt_bidimensional.mean())
#desvio padrão (standard deviation) dos valores da matriz
print(mt_bidimensional.std())

5
1
27
3.0
1.1547005383792515


In [32]:
#aplicando funções a todos itens da matriz
k1 = np.array([4,16,36,9,81])
print(np.sqrt(k1)) #raiz quadrada
print(np.exp(k1)) #valor exponencial

[2. 4. 6. 3. 9.]
[5.45981500e+01 8.88611052e+06 4.31123155e+15 8.10308393e+03
 1.50609731e+35]


In [36]:
#extracao de elementos
#elemento da posicao 2
print(k1[1])
#Mostra a partir da posição n, 2 elementos
n=1
print(k1[n:n+2])
#mostra o array da terceira posição em diante
print(k1[2:])
#mostra o array da penúltima posição até o final
print(k1[-2:])
#mostra o array da penúltima posição até a primeira
print(k1[-2::-1])

16
[16 36]
[36  9 81]
[ 9 81]
[ 9 36 16  4]


In [38]:
#extração de linhas e colunas
l = np.array([[2,3],[4,5],[6,1],[7,8]])
print(l)
#primeira linha, todas as colunas
l_linha_1 = l[0,:]
print(f"Primeira linha: {l_linha_1}")
#segunda linha
l_linha_2 = l[1,:]
print(f"Segunda linha: {l_linha_2}")
#terceira linha
l_linha_3 = l[2,:]
print(f"Terceira linha {l_linha_3}")
l_linha_4 = l[3,:]
print(f"Quarta linha {l_linha_4}")



[[2 3]
 [4 5]
 [6 1]
 [7 8]]
Primeira linha: [2 3]
Segunda linha: [4 5]
Terceira linha [6 1]
Quarta linha [7 8]


In [39]:
#todas as linhas, primeira coluna
l_coluna_1 = l[:,0]
print(f"Primeira coluna {l_coluna_1}")
l_coluna_2 = l[:,1]
print(f"Segunda coluna {l_coluna_2}")


Primeira coluna [2 4 6 7]
Segunda coluna [3 5 1 8]


In [44]:
#adição e multiplicação de matrizes
n = np.array([[2,4],[6,8]])
o = np.array([[1,3],[5,7]])
res1 = n + o
print(n,'\n',o,'\nSoma de matrizes:')
print(res1)
print('Multiplicação de matrizes')
res2 = n * o
print(res2,'\n')

p = np.array([[2,4],[8,9],[10,11],[16,23]])
q = np.array([2,1])
print(p+q)



[[2 4]
 [6 8]] 
 [[1 3]
 [5 7]] 
Soma de matrizes:
[[ 3  7]
 [11 15]]
Multiplicação de matrizes
[[ 2 12]
 [30 56]] 

[[ 4  5]
 [10 10]
 [12 12]
 [18 24]]


In [46]:
#transpoisção, rearranja um conjunto de 15 elementos de 0 a 14
f = np.arange(15).reshape((3,5))
print(f)
print('matriz transposta')
s = f.T
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
matriz transposta
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [47]:
#expressoes logicas usando where
#criando matriz com valores aleatorios positivos e negativos
mt_ale = np.random.randn(4,4)
print(mt_ale)
#criando matriz com valores booleanos
validador = (mt_ale > 0)
print(validador)
#criando matriz com valores 'positivo' ou 'negativo' baseado nas condições da 
#array validador
p_n = np.where(validador>0,'Positivo','Negativo')
print(p_n)

[[-0.03640038 -0.67584073 -0.98928317  0.84585569]
 [ 1.64744334  0.89301025 -0.42434485 -1.19641773]
 [-0.29026064 -1.20473213  1.17440234 -0.358217  ]
 [ 1.93105965 -1.12181847  0.1683064   1.42468806]]
[[False False False  True]
 [ True  True False False]
 [False False  True False]
 [ True False  True  True]]
[['Negativo' 'Negativo' 'Negativo' 'Positivo']
 ['Positivo' 'Positivo' 'Negativo' 'Negativo']
 ['Negativo' 'Negativo' 'Positivo' 'Negativo']
 ['Positivo' 'Negativo' 'Positivo' 'Positivo']]
